/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTask_ItemRequestBuilder, WithTask_ItemRequestBuilderRequestsMetadata } from './item/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/tasks/detail
 */
export interface DetailRequestBuilder extends BaseRequestBuilder<DetailRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.v1.tasks.detail.item collection
     * @param task_id Unique identifier of the item
     * @returns {WithTask_ItemRequestBuilder}
     */
     byTask_id(task_id: number) : WithTask_ItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DetailRequestBuilderUriTemplate = "{+baseurl}/api/v1/tasks/detail";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DetailRequestBuilderNavigationMetadata: Record<Exclude<keyof DetailRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTask_id: {
        requestsMetadata: WithTask_ItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["task_id"],
    },
};
/* tslint:enable */
/* eslint-enable */
