/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, createTaskFromDiscriminatorValue, serializeTask, type HTTPValidationError, type Task } from '../../../../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/tasks/update/{task_id}
 */
export interface WithTask_ItemRequestBuilder extends BaseRequestBuilder<WithTask_ItemRequestBuilder> {
    /**
     * 更新:param task_schema::param task_id::param session::return:
     * @param body データベースに永続化されたものなので id が存在する
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Task>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     put(body: Task, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Task | undefined>;
    /**
     * 更新:param task_schema::param task_id::param session::return:
     * @param body データベースに永続化されたものなので id が存在する
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: Task, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithTask_ItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/tasks/update/{task_id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTask_ItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: WithTask_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTaskFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeTask,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
